Repository kubernetes/kompose, pull requests merged in 2018-06, with the labels that each got.

#1028 Typo fix: overwite -> overwrite
  pkg/transformer/openshift/openshift.go
Labels: cncf-cla: yes, size/XS

#1030 1.14.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M

#1029 Fix invalid port name with uppercase characters
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  script/test/fixtures/multiple-compose-files/output-k8s-template.json
  script/test/fixtures/multiple-compose-files/output-os-template.json
  script/test/fixtures/same-port-different-proto/output-k8s-template.json
  script/test/fixtures/same-port-different-proto/output-os-template.json
  script/test/fixtures/v3/output-k8s-full-example.json
  script/test/fixtures/v3/output-os-full-example.json
Labels: cncf-cla: yes, size/S

#1032 Typo fix: erroring -> error
  cmd/root.go
Labels: cncf-cla: yes, size/XS

#871 Kompose will read input from stdin
  .travis.yml
  Makefile
  pkg/loader/compose/compose.go
  script/test/cmd/.coverprofile
  script/test/cmd/cmd_test.go
  script/test/cmd/tests.sh
  script/test/fixtures/stdin/output.json
  script/test_k8s/kubernetes.sh
Labels: cncf-cla: yes, size/L

#1021 Typo fix in maven-example.md
  docs/maven-example.md
Labels: cncf-cla: yes, size/XS

#1044 1.15.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M
