Repository kubernetes/kompose, pull requests merged in 2018-07, with the labels that each got.

#1041 Support node.labels at placement
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/v3.go
Labels: cncf-cla: yes, size/M

#1047 Add surajnarwade in OWNER file
  OWNERS
Labels: cncf-cla: yes, size/XS

#1020 Fix environment with env_file bug
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/env/docker-compose.yml
  script/test/fixtures/env/hadoop-hive-namenode.env
  script/test/fixtures/env/output-k8s.json
  script/test/fixtures/env/output-os.json
Labels: cncf-cla: yes, size/L

#1050 Add installation instructions for openSUSE/SLE
  README.md
  docs/installation.md
Labels: cncf-cla: yes, size/S

#1055 1.16.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M
