Repository kubernetes/kompose, pull requests merged in 2018-11, with the labels that each got.

#1075 1.17.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M

#1077 Fix typos: accecpts -> accepts
  script/test/cmd/lib.sh
Labels: cncf-cla: yes, lgtm, size/XS

#1080 Fix typo: generting -> generating
  pkg/loader/compose/v1v2.go
Labels: cncf-cla: yes, size/XS

#1079 delete excess code
  pkg/loader/compose/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1084 Fix log output specific warning info
  pkg/transformer/openshift/openshift.go
Labels: cncf-cla: yes, size/XS

#1083 Add label support to named volumes in docker compose v3 to Kubernetes
  pkg/kobject/kobject.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/volume-mounts/named-volume/docker-compose-v3.yml
  script/test/fixtures/volume-mounts/named-volume/output-k8s-v3.json
Labels: cncf-cla: yes, size/L
