Repository kubernetes/kompose, pull requests merged in 2018-05, with the labels that each got.

#997 Remove go1.6 support in ci
  .travis.yml
Labels: cncf-cla: yes, size/XS

#998 Typo fix: wil->will
  pkg/version/version.go
Labels: cncf-cla: yes, size/XS

#990 Fix missing attribute when convert with multiple docker-compose files
  pkg/loader/compose/v3.go
  script/test/cmd/tests.sh
  script/test/fixtures/merge-multiple-compose/base.yml
  script/test/fixtures/merge-multiple-compose/compose-new-service-prob.yml
  script/test/fixtures/merge-multiple-compose/compose-port-base.yml
  script/test/fixtures/merge-multiple-compose/compose-port-prod.yml
  script/test/fixtures/merge-multiple-compose/dev.yml
  script/test/fixtures/merge-multiple-compose/output-base-template.json
  script/test/fixtures/merge-multiple-compose/output-compose-new-service-template.json
  script/test/fixtures/merge-multiple-compose/output-compose-port-template.json
  script/test/fixtures/merge-multiple-compose/output-openshift-template.json
Labels: cncf-cla: yes, lgtm, size/XL

#999 Support compose global deploy mode to daemonset
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/controller/compose-global.yml
  script/test/fixtures/controller/output-k8s-global-deployment-template.json
  script/test/fixtures/controller/output-k8s-global-template.json
  script/test/fixtures/v3/output-deploy-mode-k8s-template.json
  script/test/fixtures/v3/output-deploy-mode-os-template.json
Labels: cncf-cla: yes, lgtm, size/L

#1000 Add some deprecated info warning
  cmd/convert.go
  docs/user-guide.md
Labels: cncf-cla: yes, lgtm, size/S

#1001 Add label 'kompose.controller.type' set service convert controller type
  docs/user-guide.md
  pkg/loader/compose/utils.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/controller/compose-controller-label-v3.yml
  script/test/fixtures/controller/compose-controller-label.yml
  script/test/fixtures/controller/output-k8s-controller-template.json
  script/test/fixtures/controller/output-k8s-controller-v3-template.json
  script/test/fixtures/controller/output-os-controller-v3-template.json
Labels: cncf-cla: yes, lgtm, size/XL

#1006 1.13.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M

#1011 Fix typo in integrations.md
  docs/integrations.md
Labels: cncf-cla: yes, size/XS

#1009 Fix golint warnings
  pkg/transformer/kubernetes/kubernetes.go
Labels: cncf-cla: yes, size/XS

#1018 Typo fix in tests.sh: kubernets->kubernetes
  script/test/cmd/tests.sh
Labels: cncf-cla: yes, size/XS

#1017 Update contact information for sebgoa
  OWNERS
Labels: cncf-cla: yes, size/XS

#1016 Add security contacts
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S
