Repository kubernetes/kompose, pull requests merged in 2018-04, with the labels that each got.

#977 Update dev doc about make gen-cmd
  docs/development.md
Labels: cncf-cla: yes, size/XS

#978 Fix typos in comments
  cmd/root.go
  pkg/loader/compose/compose.go
Labels: cncf-cla: yes, size/XS

#981 typo fix
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  pkg/utils/docker/push.go
Labels: cncf-cla: yes, lgtm, size/XS

#983 Fix some typo
  CHANGELOG.md
Labels: cncf-cla: yes, lgtm, size/S

#976 Support hostname and domainname
  docs/conversion.md
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  script/test/cmd/tests.sh
  script/test/fixtures/domain/docker-compose-v3.yaml
  script/test/fixtures/domain/docker-compose.yaml
  script/test/fixtures/domain/output-k8s.json
  script/test/fixtures/domain/output-os.json
  script/test/fixtures/v3/output-k8s-full-example.json
  script/test/fixtures/v3/output-os-full-example.json
Labels: cncf-cla: yes, size/L

#987 Typo fix
  pkg/app/app.go
Labels: cncf-cla: yes, lgtm, size/XS

#988 1.12.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M

#989 Fix typo in conversion.md
  docs/conversion.md
Labels: cncf-cla: yes, size/XS

#991 Remove incorrect logging about headless service
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
Labels: cncf-cla: yes, size/S

#992 Fix golint warnings
  pkg/loader/compose/utils.go
Labels: cncf-cla: yes, size/XS

#993 Fix doc that we have support v3.1 & 3.2
  docs/conversion.md
Labels: cncf-cla: yes, size/XS
