Repository kubernetes/kompose, pull requests merged in 2018-02, with the labels that each got.

#933 Refactor package app to use const rather than raw string
  pkg/app/app.go
Labels: cncf-cla: yes, size/S

#936 Fix healthcheck parser nil pointer error
  pkg/loader/compose/v3.go
  script/test/cmd/tests.sh
  script/test/fixtures/healthcheck/docker-compose-only-command.yaml
  script/test/fixtures/healthcheck/output-only-command-k8s-template.json
  script/test/fixtures/healthcheck/output-only-command-os-template.json
Labels: cncf-cla: yes, size/L

#935 Add doc for volume size label
  docs/user-guide.md
Labels: cncf-cla: yes, size/M

#937 Variable name should not be the same as imported package name
  pkg/transformer/openshift/openshift.go
Labels: cncf-cla: yes, size/M

#938 Fix custom output and charts conflict error
  pkg/transformer/kubernetes/k8sutils.go
  script/test/cmd/tests.sh
Labels: cncf-cla: yes, size/L

#920 Fixed typo
  cmd/convert.go
  cmd/up.go
Labels: cncf-cla: yes, needs-rebase, size/XS

#948 Refactor label names to const strings
  pkg/loader/compose/utils.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
Labels: cncf-cla: yes, size/S

#946 Fix image build path error
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/utils.go
  script/test_in_openshift/compose-files/buildconfig-relative-dirs/docker/docker-compose-build-image.yml
  script/test_in_openshift/compose-files/buildconfig-relative-dirs/docker_env.list
  script/test_in_openshift/compose-files/buildconfig-relative-dirs/server/Dockerfile
  script/test_in_openshift/compose-files/buildconfig-relative-dirs/web/Dockerfile
  script/test_in_openshift/tests/build.sh
Labels: cncf-cla: yes, size/M
