Repository kubernetes/kompose, pull requests merged in 2018-03, with the labels that each got.

#949 Fix broken links for volume long syntax in comments
  pkg/loader/compose/v3.go
Labels: cncf-cla: yes, size/XS

#951 1.10.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M

#950 Support old restart policy in compose v3
  docs/user-guide.md
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  script/test/cmd/tests.sh
  script/test/fixtures/restart-options/docker-compose-restart-unless-stopped.yml
  script/test/fixtures/restart-options/output-k8s-restart-unless-stopped.json
  script/test/fixtures/restart-options/output-os-restart-unless-stopped.json
Labels: cncf-cla: yes, size/L

#953 Remove bintray instructions
  README.md
  docs/installation.md
Labels: cncf-cla: yes, size/M

#960 Fix deploy resources parse error
  pkg/loader/compose/v3.go
  script/test/cmd/tests.sh
  script/test/fixtures/v3/docker-compose-memcpu-partial.yaml
  script/test/fixtures/v3/output-memcpu-partial-k8s.json
Labels: cncf-cla: yes, size/L

#957 Support hostpath volume
  cmd/convert.go
  cmd/up.go
  pkg/app/app.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/volume-mounts/hostpath/docker-compose.yml
  script/test/fixtures/volume-mounts/hostpath/output-k8s-template.json
  script/test/fixtures/volume-mounts/hostpath/output-os-template.json
Labels: cncf-cla: yes, size/L

#963 Add hangyan to OWNERS
  OWNERS
Labels: cncf-cla: yes, size/XS

#961 fix pod-controller relationship mistake
  docs/user-guide.md
Labels: cncf-cla: yes, size/XS

#956 Refactor tests script to uses vars
  script/test/cmd/tests.sh
Labels: cncf-cla: yes, size/L

#955 Add script for generating deb / rpm packages
  script/release.sh
Labels: cncf-cla: yes, size/M

#967 Fix golint warnings
  pkg/app/app.go
  pkg/loader/compose/v1v2.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/utils.go
  pkg/transformer/utils.go
  pkg/utils/docker/client.go
Labels: cncf-cla: yes, size/M

#970 1.11.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M

#973 typo fix
  pkg/utils/docker/client.go
Labels: cncf-cla: yes, size/XS

#974 Fix typos in Makefile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS
