Repository kubernetes/kompose, pull requests merged in 2019-10, with the labels that each got.

#1171 Add note about output directories to convert --help
  cmd/convert.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1174 1.19.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
  script/release.sh
Labels: cncf-cla: yes, size/L

#1151 Add node about endpoint_mode in doc
  docs/conversion.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#1177 Update OWNERS
  OWNERS
Labels: cncf-cla: yes, size/XS

#1147 Add flag to turn off push image when kompose up
  cmd/up.go
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/S
