Repository kubernetes/kompose, pull requests merged in 2019-12, with the labels that each got.

#1159 Add support for file based secret
  docs/conversion.md
  glide.yaml
  pkg/kobject/kobject.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  script/test/cmd/tests.sh
  script/test/fixtures/secrets/docker-compose-secrets-long.yml
  script/test/fixtures/secrets/docker-compose-secrets-short.yml
  script/test/fixtures/secrets/my_secret.txt
  script/test/fixtures/secrets/output-long-k8s.json
  script/test/fixtures/secrets/output-long-os.json
  script/test/fixtures/secrets/output-short-k8s.json
  script/test/fixtures/secrets/output-short-os.json
  vendor/github.com/joho/godotenv/godotenv.go
Labels: cncf-cla: yes, lifecycle/stale, size/XL

#1198 fix tests related to secrets
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/fixtures/secrets/output-long-k8s.json
  script/test/fixtures/secrets/output-long-os.json
  script/test/fixtures/secrets/output-short-k8s.json
  script/test/fixtures/secrets/output-short-os.json
Labels: cncf-cla: yes, size/M

#1197 network int test fix
  script/test/cmd/tests.sh
  script/test/fixtures/network/output-k8s.json
  script/test/fixtures/network/output-os.json
Labels: cncf-cla: yes, lgtm, size/S

#1203 1.20.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
  script/release.sh
Labels: cncf-cla: yes, size/L

#1204 Modify default kubernetes client's apiserver url
  pkg/transformer/kubernetes/kubernetes.go
Labels: cncf-cla: yes, size/M

#1205 Fix chart lint
  pkg/transformer/kubernetes/k8sutils.go
Labels: cncf-cla: yes, size/XS

#1206 Remove duplicate of configmap
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  script/test/fixtures/configmap/output-k8s-template.json
  script/test/fixtures/env/docker-compose.yml
  script/test/fixtures/env/output-k8s.json
  script/test/fixtures/env/output-os.json
Labels: cncf-cla: yes, size/L

#1208 Add flag to support store manifest when kompose up
  cmd/up.go
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/kubernetes.go
Labels: cncf-cla: yes, size/S

#1209 Use new go version for build
  .travis.yml
Labels: cncf-cla: yes, size/XS

#1210 Support assign nodeport port in labels
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/loader/compose/utils.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/service-label/docker-compose.yaml
  script/test/fixtures/service-label/output-k8s.json
  script/test/fixtures/service-label/output-oc.json
Labels: cncf-cla: yes, size/L

#1212 Fix build
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  pkg/transformer/utils.go
  script/test/cmd/lib.sh
  script/test/cmd/tests.sh
Labels: cncf-cla: yes, size/M

#1213 Use service name when image name is empty when build
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
Labels: cncf-cla: yes, size/S

#1214 Merge will include deploy resources
  pkg/loader/compose/v3.go
  script/test/fixtures/merge-multiple-compose/dev.yml
  script/test/fixtures/merge-multiple-compose/output-base-template.json
Labels: cncf-cla: yes, size/S

#1216 Support use configmap as volume
  cmd/convert.go
  pkg/app/app.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/configmap-volume/docker-compose.yml
  script/test/fixtures/configmap-volume/output-k8s.json
  script/test/fixtures/configmap-volume/output-oc.json
  script/test/fixtures/configmap-volume/tls/a.crt
  script/test/fixtures/configmap-volume/tls/a.key
Labels: cncf-cla: yes, size/L

#1219 Yaml indent
  cmd/convert.go
  glide.lock
  glide.yaml
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/k8sutils.go
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
Labels: cncf-cla: yes, size/XXL

#1220 Add note adout windows
  README.md
Labels: cncf-cla: yes, size/XS

#1221 Fix hostpath path translate error
  pkg/loader/compose/v1v2.go
  script/test/cmd/tests.sh
  script/test/fixtures/volume-mounts/hostpath/docker-compose.yml
  script/test/fixtures/volume-mounts/hostpath/output-k8s-template.json
  script/test/fixtures/volume-mounts/hostpath/output-os-template.json
Labels: cncf-cla: yes, size/S

#1222 Fix v3 hostpath path error
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/volume-mounts/hostpath/docker-compose-v3.yml
Labels: cncf-cla: yes, size/M

#1223 Fix port duplicate in container spec
  pkg/transformer/kubernetes/kubernetes.go
  script/test/fixtures/multiple-compose-files/output-k8s-template.json
  script/test/fixtures/multiple-compose-files/output-os-template.json
  script/test/fixtures/ports-with-proto/docker-compose.yml
  script/test/fixtures/ports-with-proto/output-k8s-template.json
  script/test/fixtures/ports-with-proto/output-os-template.json
  script/test/fixtures/v3/output-k8s-full-example.json
  script/test/fixtures/v3/output-os-full-example.json
Labels: cncf-cla: yes, size/M
