Repository kubernetes/kompose, pull requests merged in 2019-03, with the labels that each got.

#1108 1.18.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/M

#1115 Update embargo doc link in SECURITY_OWNERS and change PST to PSC
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS

#1118 Remove ROADMAP.md
  README.md
  ROADMAP.md
Labels: approved, cncf-cla: yes, size/M

#1112 Fix function comments based on best practices from Effective Go
  pkg/transformer/utils.go
Labels: cncf-cla: yes, lgtm, size/XS
