Repository kubernetes/kompose, pull requests merged in 2019-06, with the labels that each got.

#1139 Submodule with a 'go get'-friendly url
  .gitmodules
Labels: cncf-cla: yes, lgtm, size/XS

#1123 Add node references
  README.md
  docs/getting-started.md
  docs/introduction.md
  docs/user-guide.md
  examples/docker-compose-v3.yaml
  examples/docker-compose.yaml
  script/test/fixtures/controller/docker-compose.yml
  script/test/fixtures/controller/output-k8s-daemonset-template.json
  script/test/fixtures/controller/output-k8s-deployment-template.json
  script/test/fixtures/controller/output-k8s-rc-template.json
  script/test/fixtures/examples/output-k8s.json
  script/test/fixtures/examples/output-os.json
  script/test/fixtures/examples/output-v3-k8s.json
  script/test/fixtures/examples/output-v3-os.json
  script/test/fixtures/keyonly-envs/env.yml
  script/test/fixtures/keyonly-envs/output-k8s-template.json
  script/test/fixtures/v3/docker-compose.yaml
  script/test/fixtures/v3/output-k8s-template.json
  script/test/fixtures/v3/output-os-template.json
Labels: cncf-cla: yes, lgtm, size/L

#1141 Fix container_name set error
  pkg/transformer/kubernetes/k8sutils.go
  script/test/fixtures/v3/docker-compose-full-example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1145 Revert "Add node references"
  README.md
  docs/getting-started.md
  docs/introduction.md
  docs/user-guide.md
  examples/docker-compose-v3.yaml
  examples/docker-compose.yaml
  script/test/fixtures/controller/docker-compose.yml
  script/test/fixtures/controller/output-k8s-daemonset-template.json
  script/test/fixtures/controller/output-k8s-deployment-template.json
  script/test/fixtures/controller/output-k8s-rc-template.json
  script/test/fixtures/examples/output-k8s.json
  script/test/fixtures/examples/output-os.json
  script/test/fixtures/examples/output-v3-k8s.json
  script/test/fixtures/examples/output-v3-os.json
  script/test/fixtures/keyonly-envs/env.yml
  script/test/fixtures/keyonly-envs/output-k8s-template.json
  script/test/fixtures/v3/docker-compose.yaml
  script/test/fixtures/v3/output-k8s-template.json
  script/test/fixtures/v3/output-os-template.json
Labels: cncf-cla: yes, lgtm, size/L
