Repository kubernetes/kompose, pull requests merged in 2020-11, with the labels that each got.

#1335 Support podman compose file
  pkg/app/app.go
Labels: approved, cncf-cla: yes, size/S

#1336 The Red Hat Development Suite has been discontinued
  docs/getting-started.md
Labels: cncf-cla: yes, size/XS

#1338 fix invalid repo url
  docs/installation.md
Labels: cncf-cla: yes, size/XS

#1339 fix invalid repo url for SUSE Linux Enterprise 15
  docs/installation.md
Labels: cncf-cla: yes, size/XS

#1340 Allow controller pod to override restart policy
  go.mod
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
Labels: approved, cncf-cla: yes, size/S

#1341 Lb svc
  d.yaml
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  script/test/fixtures/v2/docker-compose.yaml
  script/test/fixtures/v2/output-k8s.json
  script/test/fixtures/v2/output-os.json
Labels: approved, cncf-cla: yes, size/L

#1342 Update docs
  README.md
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
Labels: approved, cncf-cla: yes, size/XS

#1343 make kompose exit with 1 if error
  cmd/root.go
  main.go
Labels: cncf-cla: yes, size/S

#1344 Follow up on #1341
  examples/docker-compose-loadbalancer-with-mixed-protocols.yaml
  pkg/transformer/kubernetes/kubernetes.go
Labels: cncf-cla: yes, size/XS

#1345 Support port range for docker-compose v2
  go.mod
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  script/test/fixtures/v2/docker-compose.yaml
  script/test/fixtures/v2/output-k8s.json
  script/test/fixtures/v2/output-os.json
Labels: cncf-cla: yes, size/XL

#1348 cleanup debug logs & remove duplicated output
  cmd/root.go
  main.go
  pkg/transformer/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, size/S

#1349 improve tests for loadV3Ports
  pkg/loader/compose/compose_test.go
Labels: cncf-cla: yes, size/M

#1351 retrieve container test by updating Dockerfile
  go.sum
  script/test_in_container/Dockerfile
Labels: cncf-cla: yes, size/S

#1350 Create directories if --out ends with "/" or includes nonexistent directories
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/utils.go
  script/test/cmd/tests.sh
  script/test/cmd/tests_new.sh
Labels: approved, cncf-cla: yes, size/M

#1353 Cleanup glide
  CONTRIBUTING.md
  Jenkinsfile
  Makefile
  docs/development.md
  go.mod
  go.sum
  script/check-vendor.sh
Labels: approved, cncf-cla: yes, size/L

#1355 Migrate CI from travis ci to github actions
  .github/workflows/test.yml
  .travis.yml
  script/generate-bintray-json.sh
  script/sync-docs.sh
  script/test_in_openshift/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1356 GitHub Actions Part2
  .github/workflows/test.yml
  README.md
  script/test_in_openshift/lib.sh
Labels: approved, cncf-cla: yes, size/S

#1317 TLS improvements
  .github/workflows/go.yml
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/utils.go
Labels: cncf-cla: yes, size/M
