Repository kubernetes/kompose, pull requests merged in 2020-02, with the labels that each got.

#1242 Add MacPorts support to the documentation
  README.md
  docs/installation.md
Labels: cncf-cla: yes, size/XS

#1243 Add flag to allow use define api server url
  cmd/up.go
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/kubernetes.go
Labels: cncf-cla: yes, size/L

#1244 Support v2 restart unless-stopped
  pkg/loader/compose/v1v2.go
Labels: cncf-cla: yes, size/XS

#1245 Support ingress path for kubernetes
  docs/user-guide.md
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/utils.go
  script/test/fixtures/expose-service/compose-files/docker-compose-expose-multiple-hostname.yml
  script/test/fixtures/expose-service/provider-files/kubernetes-expose-multiple-hostname.json
Labels: cncf-cla: yes, size/S
