Repository kubernetes/kompose, pull requests merged in 2020-01, with the labels that each got.

#1225 Update doc about push image
  docs/user-guide.md
Labels: cncf-cla: yes, size/XS

#1226 concat and merge service fields when merging compose files (#1186)
  pkg/loader/compose/v3.go
  script/test/cmd/tests.sh
  script/test/fixtures/merge-multiple-compose/output-compose-new-service-template.json
  script/test/fixtures/merge-multiple-compose/output-compose-port-template.json
  script/test/fixtures/merge-multiple-compose/output-openshift-template.json
  script/test/fixtures/merge-multiple-compose/output-service-merge-concat-template.json
  script/test/fixtures/merge-multiple-compose/service-merge-concat-base.yml
  script/test/fixtures/merge-multiple-compose/service-merge-concat-override.yml
Labels: cncf-cla: yes, lgtm, size/L

#1227 Support port expose
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/fixtures/merge-multiple-compose/output-service-merge-concat-template.json
  script/test/fixtures/ports-with-proto/docker-compose.yml
  script/test/fixtures/ports-with-proto/output-k8s-template.json
  script/test/fixtures/ports-with-proto/output-os-template.json
  script/test/fixtures/v3/docker-compose-3.5.yaml
  script/test/fixtures/v3/output-k8s-3.5.json
Labels: cncf-cla: yes, size/L

#1228 Refactor code
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
Labels: cncf-cla: yes, size/L

#1230 Support config short syntax and fix old bugs
  docs/conversion.md
  pkg/kobject/kobject.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/compose-v3.3-test/output-k8s-config-long-warning.json
  script/test/fixtures/compose-v3.3-test/output-k8s-config-long.json
  script/test/fixtures/compose-v3.3-test/output-k8s-config-short-warning.json
  script/test/fixtures/compose-v3.3-test/output-k8s-config-short.json
  script/test/fixtures/compose-v3.3-test/output-os-config-long.json
  script/test/fixtures/compose-v3.3-test/output-os-config-short.json
  script/test/fixtures/merge-multiple-compose/output-other-toplevel-merge-template.json
  script/test/fixtures/merge-multiple-compose/output-other-toplevel-override-template.json
Labels: cncf-cla: yes, size/L

#1231 Support deploy labels
  docs/conversion.md
  pkg/kobject/kobject.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/utils.go
  script/test/fixtures/v3/docker-compose-deploy-mode.yaml
  script/test/fixtures/v3/output-deploy-mode-k8s-template.json
  script/test/fixtures/v3/output-deploy-mode-os-template.json
Labels: cncf-cla: yes, size/L

#1232 Deploy config
  docs/conversion.md
  pkg/kobject/kobject.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  script/test/cmd/tests.sh
  script/test/fixtures/placement/docker-compose-array.yml
  script/test/fixtures/placement/docker-compose.yml
  script/test/fixtures/placement/output-k8s-array-template.json
  script/test/fixtures/placement/output-k8s-template.json
  script/test/fixtures/placement/output-os-array-template.json
  script/test/fixtures/placement/output-os-template.json
  script/test/fixtures/v3/docker-compose-deploy-mode.yaml
  script/test/fixtures/v3/docker-compose-deploy.yaml
  script/test/fixtures/v3/output-deploy-k8s.json
  script/test/fixtures/v3/output-deploy-mode-k8s-template.json
  script/test/fixtures/v3/output-deploy-os.json
Labels: cncf-cla: yes, size/XXL

#1233 Fix some ci lint
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/openshift/openshift.go
  pkg/transformer/utils.go
Labels: cncf-cla: yes, size/S
