Repository kubernetes/kompose, pull requests merged in 2020-08, with the labels that each got.

#1299 Update user guide
  docs/user-guide.md
Labels: cncf-cla: yes, size/L

#1300 fix stop_grace_period in v3
  pkg/loader/compose/v3.go
  script/test/fixtures/v3/output-k8s-full-example.json
  script/test/fixtures/v3/output-os-full-example.json
Labels: cncf-cla: yes, size/S

#1302 Remove networkpolicy dup
  pkg/transformer/kubernetes/k8sutils.go
Labels: cncf-cla: yes, size/S

#1303 Add missing pod ano
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests.sh
  script/test/fixtures/restart-options/output-k8s-restart-no.json
  script/test/fixtures/restart-options/output-k8s-restart-onfail.json
  script/test/fixtures/restart-options/output-os-restart-no.json
  script/test/fixtures/restart-options/output-os-restart-onfail.json
  script/test/fixtures/v3/output-k8s-full-example.json
  script/test/fixtures/v3/output-os-full-example.json
Labels: cncf-cla: yes, size/M

#1307 Update networkpolicy version
  pkg/transformer/kubernetes/kubernetes.go
  script/test/fixtures/v3.0/docker-compose.yaml
  script/test/fixtures/v3.0/output-k8s.json
  script/test/fixtures/v3.0/output-os.json
Labels: cncf-cla: yes, size/L
