Repository kubernetes/kompose, pull requests merged in 2020-03, with the labels that each got.

#1257 Add support for push-image with --build local
  cmd/convert.go
Labels: cncf-cla: yes, lgtm, size/XS

#1255 Fix printing docker build output if -v is given
  pkg/utils/docker/build.go
Labels: cncf-cla: yes, lgtm, size/XS

#1260 Add server flag for kompose down
  Makefile
  cmd/down.go
  cmd/up.go
  docs/user-guide.md
Labels: cncf-cla: yes, size/S

#1256 Add support for build-args with --build local
  pkg/transformer/utils.go
  pkg/utils/docker/build.go
Labels: cncf-cla: yes, size/S

#1266 Add arm64 to make cross
  Makefile
Labels: cncf-cla: yes, size/XS

#1248 Fix annotations missing for ingress
  pkg/transformer/kubernetes/kubernetes.go
  script/test/fixtures/expose-service/provider-files/kubernetes-expose-hostname-multiple-ports.json
  script/test/fixtures/expose-service/provider-files/kubernetes-expose-hostname-tls.json
  script/test/fixtures/expose-service/provider-files/kubernetes-expose-hostname.json
  script/test/fixtures/expose-service/provider-files/kubernetes-expose-multiple-hostname-tls.json
  script/test/fixtures/expose-service/provider-files/kubernetes-expose-multiple-hostname.json
  script/test/fixtures/expose-service/provider-files/kubernetes-expose-true-multiple-ports.json
  script/test/fixtures/expose-service/provider-files/kubernetes-expose-true.json
Labels: cncf-cla: yes, size/M
