Repository kubernetes/kompose, pull requests merged in 2020-10, with the labels that each got.

#1329 1.22.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
Labels: approved, cncf-cla: yes, size/L

#1330 Update introduction doc + add sync docs script
  docs/introduction.md
  script/manual-docs-sync.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1332 update year to 2020
  _config.yml
Labels: cncf-cla: yes

#1331 Update doc about helm chart format
  docs/user-guide.md
Labels: approved, cncf-cla: yes, size/XS

#1326 add warning that tells why the service is not created
  pkg/transformer/kubernetes/kubernetes.go
Labels: cncf-cla: yes, lgtm, size/XS

#1333 Add support for compose 2.x
  go.mod
  go.sum
  pkg/loader/compose/compose.go
Labels: approved, cncf-cla: yes, size/S

#1334 Bump docker version
  go.mod
  go.sum
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/loader/compose/compose_test.go
Labels: approved, cncf-cla: yes, size/L
