Repository kubernetes/kompose, pull requests merged in 2021-11, with the labels that each got.

#1452 Add initial support for statefulset controller.
  docs/user-guide.md
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/statefulset/docker-compose.yaml
  script/test/fixtures/statefulset/output-k8s.json
  script/test/fixtures/statefulset/output-os.json
Labels: cncf-cla: yes, size/XL, approved

#1425 Add support for placement preferences docker-compose v3.3+
  pkg/kobject/kobject.go
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/kubernetes/podspec.go
  script/test/fixtures/deploy/placement/docker-compose-placement.yaml
  script/test/fixtures/deploy/placement/output-placement-k8s.json
  script/test/fixtures/deploy/placement/output-placement-os.json
  script/test/fixtures/unused/v3/output-deploy-k8s.json
  script/test/fixtures/unused/v3/output-deploy-os.json
Labels: cncf-cla: yes, size/L

#1455 Add make rule for darwin arm64 in cross target
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#1456 Infer storage type using label
  docs/user-guide.md
  pkg/app/app.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/configmap-volume/docker-compose-withlabel.yml
  script/test/fixtures/configmap-volume/output-k8s-withlabel.json
  script/test/fixtures/configmap-volume/output-os-withlabel.json
  script/test/fixtures/multiple-type-volumes/docker-compose.yaml
  script/test/fixtures/multiple-type-volumes/output-k8s.json
  script/test/fixtures/multiple-type-volumes/output-os.json
  script/test/fixtures/multiple-type-volumes/tls/a.crt
  script/test/fixtures/multiple-type-volumes/tls/a.key
Labels: cncf-cla: yes, size/XXL

#1460 1.26.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/README.md
  docs/architecture.md
  docs/conversion.md
  docs/development.md
  docs/getting-started.md
  docs/installation.md
  docs/integrations.md
  docs/maven-example.md
  docs/user-guide.md
  gover.coverprofile
  index.md
  pkg/version/version.go
  script/deploy_key
Labels: cncf-cla: no, size/XXL, approved

#1461 Fix ImageStream tags in openshift provider mode
  pkg/transformer/openshift/openshift.go
  script/test/fixtures/change-in-volume/output-os-empty-vols-template.json
  script/test/fixtures/configmap-volume/output-os-withlabel.json
  script/test/fixtures/configmap-volume/output-os.json
  script/test/fixtures/deploy/placement/output-placement-os.json
  script/test/fixtures/expose/output-ocp.json
  script/test/fixtures/healthcheck/output-healthcheck-os.json
  script/test/fixtures/multiple-files/output-ocp.json
  script/test/fixtures/multiple-type-volumes/output-os.json
  script/test/fixtures/pvc-request-size/output-os.json
  script/test/fixtures/statefulset/output-os.json
  script/test/fixtures/storage-class-name/output-os.json
  script/test/fixtures/v2/output-os.json
  script/test/fixtures/v3.0/output-os.json
  script/test/fixtures/volume-mounts/windows/output-os.json
Labels: cncf-cla: yes, size/M
