Repository kubernetes/kompose, pull requests merged in 2021-08, with the labels that each got.

#1402 chore: update error for wrong volume type
  pkg/app/app.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1404 Fix the selector field of service resource
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  script/test/fixtures/v2/output-k8s.json
  script/test/fixtures/v2/output-os.json
Labels: lgtm, cncf-cla: yes, size/S, approved

#1405 fix: --build flag default change to local
  cmd/convert.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1406 Add "--pvc-request-size" new command line parameter
  cmd/convert.go
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/pvc-request-size/docker-compose.yml
  script/test/fixtures/pvc-request-size/output-k8s.json
  script/test/fixtures/pvc-request-size/output-os.json
Labels: cncf-cla: yes, size/XL

#1411 Fix build context
  pkg/loader/compose/v3.go
  pkg/transformer/utils.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/buildconfig/docker-compose-v3.yml
Labels: lgtm, cncf-cla: yes, size/M, approved

#1412 add autocompletion for fish shell
  README.md
  cmd/completion.go
Labels: cncf-cla: yes, size/M

#1409 Support custom registry on pushing image
  cmd/convert.go
  docs/conversion.md
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  pkg/transformer/utils.go
  pkg/utils/docker/image.go
  pkg/utils/docker/image_test.go
  pkg/utils/docker/push.go
  pkg/utils/docker/tag.go
  script/test/cmd/tests_new.sh
  script/test/cmd/tests_push_image.sh
Labels: lgtm, cncf-cla: yes, size/L, approved

#1401 Add ServiceAccountName
  docs/user-guide.md
  pkg/loader/compose/utils.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/kubernetes/podspec.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1413 Add storageClassName label to persistent volume claim manifest in doc…
  docs/user-guide.md
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/storage-class-name/docker-compose.yml
  script/test/fixtures/storage-class-name/output-k8s.json
  script/test/fixtures/storage-class-name/output-os.json
Labels: cncf-cla: yes, size/L

#1414 fix kompose.image-pull-secret invalid when use compose configs
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
Labels: cncf-cla: yes, size/M

#1417 Add parse windows volume
  pkg/transformer/utils.go
  pkg/transformer/utils_test.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/volume-mounts/windows/docker-compose.yaml
  script/test/fixtures/volume-mounts/windows/output-k8s.json
  script/test/fixtures/volume-mounts/windows/output-os.json
Labels: cncf-cla: yes, size/XL

#1423 Fix misuse in struct kobject.ServiceConfig.Port
  pkg/kobject/kobject.go
  pkg/loader/bundle/bundle.go
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/openshift/openshift_test.go
Labels: cncf-cla: yes, size/L

#1424 1.24.0 Release
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
  script/release.sh
Labels: cncf-cla: yes, size/L, approved
