Repository kubernetes/kompose, pull requests merged in 2021-10, with the labels that each got.

#1435 Remove code for parsing DAB files
  cmd/convert.go
  cmd/root.go
  docs/architecture.md
  docs/images/design_diagram.png
  pkg/app/app.go
  pkg/loader/bundle/bundle.go
  pkg/loader/bundle/bundle_test.go
  pkg/loader/loader.go
Labels: cncf-cla: yes, size/L, approved

#1436 Upgrade Ingress apiversion
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/expose/compose.yaml
  script/test/fixtures/expose/output-k8s.json
  script/test/fixtures/expose/output-ocp.json
  script/test/fixtures/unused/expose-service/compose-files/docker-compose-expose-hostname-multiple-ports.yml
  script/test/fixtures/unused/expose-service/compose-files/docker-compose-expose-hostname-tls.yml
  script/test/fixtures/unused/expose-service/compose-files/docker-compose-expose-hostname.yml
  script/test/fixtures/unused/expose-service/compose-files/docker-compose-expose-multiple-hostname-tls.yml
  script/test/fixtures/unused/expose-service/compose-files/docker-compose-expose-multiple-hostname.yml
  script/test/fixtures/unused/expose-service/compose-files/docker-compose-expose-true-multiple-ports.yml
  script/test/fixtures/unused/expose-service/compose-files/docker-compose-expose-true.yml
  script/test/fixtures/unused/expose-service/provider-files/kubernetes-expose-hostname-multiple-ports.json
  script/test/fixtures/unused/expose-service/provider-files/kubernetes-expose-hostname-tls.json
  script/test/fixtures/unused/expose-service/provider-files/kubernetes-expose-hostname.json
  script/test/fixtures/unused/expose-service/provider-files/kubernetes-expose-multiple-hostname-tls.json
  script/test/fixtures/unused/expose-service/provider-files/kubernetes-expose-multiple-hostname.json
  script/test/fixtures/unused/expose-service/provider-files/kubernetes-expose-true-multiple-ports.json
  script/test/fixtures/unused/expose-service/provider-files/kubernetes-expose-true.json
  script/test/fixtures/unused/expose-service/provider-files/openshift-expose-hostname-multiple-ports.json
  script/test/fixtures/unused/expose-service/provider-files/openshift-expose-hostname.json
  script/test/fixtures/unused/expose-service/provider-files/openshift-expose-true-multiple-ports.json
  script/test/fixtures/unused/expose-service/provider-files/openshift-expose-true.json
  script/test/fixtures/unused/v3/docker-compose-3.5.yaml
  script/test/fixtures/unused/v3/docker-compose-deploy.yaml
  script/test/fixtures/unused/v3/docker-compose-env-subs.yaml
  script/test/fixtures/unused/v3/docker-compose-env.yaml
  script/test/fixtures/unused/v3/docker-compose-full-example.yaml
  script/test/fixtures/unused/v3/docker-compose-memcpu-partial.yaml
  script/test/fixtures/unused/v3/docker-compose-memcpu.yaml
  script/test/fixtures/unused/v3/docker-compose-unset-env.yaml
  script/test/fixtures/unused/v3/docker-compose-volumes.yaml
  script/test/fixtures/unused/v3/docker-compose.yaml
  script/test/fixtures/unused/v3/example1.env
  script/test/fixtures/unused/v3/example2.env
  script/test/fixtures/unused/v3/output-deploy-k8s.json
  script/test/fixtures/unused/v3/output-deploy-os.json
  script/test/fixtures/unused/v3/output-env-k8s.json
  script/test/fixtures/unused/v3/output-env-subs.json
  script/test/fixtures/unused/v3/output-k8s-3.5.json
  script/test/fixtures/unused/v3/output-k8s-full-example-template.json
  script/test/fixtures/unused/v3/output-k8s-full-example.json
  script/test/fixtures/unused/v3/output-k8s-template.json
  script/test/fixtures/unused/v3/output-memcpu-k8s.json
  script/test/fixtures/unused/v3/output-memcpu-partial-k8s.json
  script/test/fixtures/unused/v3/output-os-full-example.json
  script/test/fixtures/unused/v3/output-os-template.json
  script/test/fixtures/unused/v3/output-unset-env-k8s.json
  script/test/fixtures/unused/v3/output-volumes-k8s-template.json
Labels: cncf-cla: yes, size/XL, approved

#1437 Update golang versions in ci
  .github/workflows/go.yml
  .github/workflows/test.yml
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved

#1438 Refactor
  pkg/loader/compose/utils.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/kubernetes/podspec.go
  pkg/transformer/openshift/openshift.go
  pkg/transformer/utils.go
Labels: cncf-cla: yes, size/L, approved

#1439 Support group service by shared volumes
  .github/workflows/go.yml
  cmd/convert.go
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/kubernetes/podspec.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/service-group/compose.yaml
  script/test/fixtures/service-group/output-k8s.json
Labels: cncf-cla: yes, size/L, approved
