Repository kubernetes/kompose, pull requests merged in 2021-07, with the labels that each got.

#1393 actually use normalizeNetworkNames to produce valid network names
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/utils.go
  pkg/loader/compose/v1v2.go
Labels: cncf-cla: yes, size/S

#1394 support multiple containers in a pod
  cmd/convert.go
  docs/user-guide.md
  go.mod
  go.sum
  pkg/kobject/kobject.go
  pkg/loader/compose/utils.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/kubernetes/podspec.go
Labels: cncf-cla: yes, size/XL

#1398 Release 1.23.0
  CHANGELOG.md
  README.md
  build/VERSION
  docs/installation.md
  docs/introduction.md
  pkg/version/version.go
  script/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
