Repository kubernetes/kompose, pull requests merged in 2021-05, with the labels that each got.

#1378 Fix convert deployment log error
  go.mod
  pkg/transformer/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, size/S

#1379 Fix secret name error
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, size/S

#1380 Fix labels merge error
  pkg/loader/compose/v3.go
Labels: approved, cncf-cla: yes, size/XS

#1382 Fix intro doc error
  docs/introduction.md
Labels: approved, cncf-cla: yes, size/XS

#1386 Fixed, #1385
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/utils.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
Labels: cncf-cla: yes, lgtm, size/L
