Repository kubernetes/kompose, pull requests merged in 2022-08, with the labels that each got.

#1515 fix: change the port ID definition in kubernetes.go file
  pkg/kobject/kobject.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/kubernetes/podspec.go
Labels: cncf-cla: yes, size/S

#1512 fix daemonset creation (add selector)
  pkg/transformer/kubernetes/kubernetes.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1496 Provide updated installation instructions for openSUSE/SLE (#1495)
  docs/installation.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1478 Fixed secret file locations to match results from docker-compose when using file-based secrets
  cmd/convert.go
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/kubernetes.go
Labels: lgtm, cncf-cla: yes, size/L, approved
