Repository kubernetes/kompose, pull requests merged in 2022-11, with the labels that each got.

#1531 Fix(CI Pipeline): Update Kubernetes unit tests and CI Pipeline configuration files
  .github/workflows/golangci-lint.yml
  go.mod
  go.sum
  pkg/transformer/kubernetes/kubernetes_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1535 Update release script
  script/release.sh
Labels: cncf-cla: yes, size/L, approved

#1536 remove sync docs from ci
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/XS, approved

#1524 Fix environment variables interpolation
  pkg/kobject/kobject.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/podspec.go
  pkg/utils/docker/image.go
  pkg/utils/docker/tag.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/envvars-interpolation/docker-compose.yaml
  script/test/fixtures/envvars-interpolation/output-k8s.json
  script/test/fixtures/envvars-interpolation/output-os.json
Labels: cncf-cla: yes, size/L, approved

#1516 fix all known trivy scan vulnerabilities
  docs/Gemfile.lock
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved

#1538 Test: Update e2e tests [WIP]
  pkg/kobject/kobject.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/fixtures/expose/compose.yaml
  script/test/fixtures/expose/output-ocp.json
  script/test/fixtures/service-group/output-k8s.json
  script/test/fixtures/statefulset/output-os.json
  script/test/fixtures/v2/output-os.json
Labels: lgtm, cncf-cla: yes, size/M, approved

#1540 Add AhmedGrati to kompose OWNERS
  OWNERS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS
