Repository kubernetes/kompose, pull requests merged in 2022-01, with the labels that each got.

#1468 Added more installation instructions
  README.md
  docs/installation.md
Labels: cncf-cla: yes, size/M

#1477 Synchronize site and update .gitignore
  .gitignore
  docs/_layouts/index.html
Labels: cncf-cla: yes, size/XS

#1476 Update README for docs website
  docs/README.md
Labels: cncf-cla: yes, size/XS, approved
