Repository kubernetes/kompose, pull requests merged in 2023-02, with the labels that each got.

#1567 k8sutils: Update helm template to use apiVersion v2
  pkg/transformer/kubernetes/k8sutils.go
Labels: cncf-cla: yes, size/XS, approved

#1557 Fixes typos
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RELEASE.md
  build/README.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/architecture.md
  docs/conversion.md
  docs/development.md
  docs/getting-started.md
  docs/index.md
  docs/installation.md
  docs/integrations.md
  docs/maven-example.md
  docs/user-guide.md
  go.mod
  index.md
Labels: cncf-cla: yes, size/XL

#1574 Adds a new logo for Kompose
  .gitignore
  README.md
  docs/assets/favicons/android-chrome-192x192.png
  docs/assets/favicons/android-chrome-256x256.png
  docs/assets/favicons/android-chrome-384x384.png
  docs/assets/favicons/apple-touch-icon.png
  docs/assets/favicons/favicon-16x16.png
  docs/assets/favicons/favicon-32x32.png
  docs/assets/favicons/favicon.ico
  docs/assets/favicons/mstile-150x150.png
  docs/assets/favicons/safari-pinned-tab.svg
  docs/assets/images/logo.png
  docs/assets/images/logo.xcf
  docs/assets/images/logo_large.png
  docs/favicon.ico
Labels: cncf-cla: yes, size/S, approved

#1569 change master to main in scripts and docs
  .github/workflows/go.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Makefile
  README.md
  docs/development.md
  docs/getting-started.md
  docs/installation.md
  docs/maven-example.md
  script/test_in_container/Dockerfile
Labels: cncf-cla: yes, size/M, approved

#1575 docs: update installation doc
  docs/installation.md
Labels: cncf-cla: yes, size/M, approved

#1578 update sync script again
  script/manual-docs-sync.sh
Labels: cncf-cla: yes, size/S, approved

#1560 Feat: Add issues and pull requests templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, size/L, approved

#1580 Fix TOC on site / documentation
  docs/architecture.md
  docs/conversion.md
  docs/getting-started.md
  docs/installation.md
  docs/integrations.md
  docs/user-guide.md
Labels: cncf-cla: yes, size/S, approved

#1525 support build with docker cli
  pkg/utils/docker/build.go
Labels: cncf-cla: yes, size/M

#1559 feat: integrate pre-commit hooks
  .pre-commit-config.yaml
Labels: cncf-cla: yes, size/S, approved

#1586 fix: support host port and protocol in functional tests
  script/test/fixtures/change-in-volume/output-k8s-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-os-empty-vols-template.yaml
  script/test/fixtures/deploy/placement/output-placement-k8s.yaml
  script/test/fixtures/deploy/placement/output-placement-os.yaml
  script/test/fixtures/expose/output-k8s.yaml
  script/test/fixtures/expose/output-os.yaml
  script/test/fixtures/healthcheck/output-healthcheck-k8s.yaml
  script/test/fixtures/healthcheck/output-healthcheck-os.yaml
  script/test/fixtures/service-group/output-k8s.yaml
  script/test/fixtures/single-file-output/output-k8s.yaml
  script/test/fixtures/statefulset/output-k8s.yaml
  script/test/fixtures/statefulset/output-os.yaml
  script/test/fixtures/v2/output-k8s.yaml
  script/test/fixtures/v2/output-os.yaml
  script/test/fixtures/volume-mounts/windows/output-k8s.yaml
  script/test/fixtures/volume-mounts/windows/output-os.yaml
Labels: cncf-cla: yes, size/L, approved

#1544 Feat support external traffic policy
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/loader/compose/utils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/openshift/openshift.go
  pkg/transformer/openshift/openshift_test.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/external-traffic-policy/docker-compose-v1.yaml
  script/test/fixtures/external-traffic-policy/docker-compose-v2.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v1.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v2.yaml
  script/test/fixtures/external-traffic-policy/output-os-v1.yaml
  script/test/fixtures/external-traffic-policy/output-os-v2.yaml
  script/test/fixtures/v3.0/docker-compose.yaml
  script/test/fixtures/v3.0/output-k8s.yaml
  script/test/fixtures/v3.0/output-os.yaml
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1588 Fix docs regarding building from container
  docs/installation.md
Labels: cncf-cla: yes, size/XS, approved

#1589 Update copyright website 2023
  docs/_config.yml
Labels: cncf-cla: yes, size/XS, approved

#1590 Update references from k8s.gcr.io to registry.k8s.io
  examples/docker-compose-v3.yaml
  examples/docker-compose.yaml
  script/test/fixtures/controller/docker-compose.yml
  script/test/fixtures/controller/output-k8s-daemonset-template.json
  script/test/fixtures/controller/output-k8s-deployment-template.json
  script/test/fixtures/controller/output-k8s-rc-template.json
  script/test/fixtures/examples/output-k8s.json
  script/test/fixtures/examples/output-os.json
  script/test/fixtures/examples/output-v3-k8s.json
  script/test/fixtures/examples/output-v3-os.json
  script/test/fixtures/keyonly-envs/env.yml
  script/test/fixtures/keyonly-envs/output-k8s-template.json
  script/test/fixtures/unused/v3/docker-compose.yaml
  script/test/fixtures/unused/v3/output-k8s-template.json
  script/test/fixtures/unused/v3/output-os-template.json
  script/test/fixtures/volume-mounts/tmpfs/docker-compose.yml
  script/test/fixtures/volume-mounts/tmpfs/output-k8s-template.json
  script/test/fixtures/volume-mounts/tmpfs/output-os-template.json
Labels: lgtm, cncf-cla: yes, size/M, approved
