Repository kubernetes/kompose, pull requests merged in 2023-11, with the labels that each got.

#1750 chore: add warning when no service is selected
  pkg/loader/compose/compose.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/no-profile-warning/docker-compose.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/S, approved

#1749 test: add unit tests for pr 1743
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1752 test: add unit-test for PR 1743 v2
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1753 feat: Add `COMPOSE_FILE` env variable
  cmd/root.go
  docs/user-guide.md
  script/test/cmd/tests_new.sh
  script/test/fixtures/compose-file-env-variable/alternative-docker-compose.yaml
  script/test/fixtures/compose-file-env-variable/docker-compose.yaml
  script/test/fixtures/compose-file-env-variable/output-k8s.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/L, approved

#1754 fix: disable annotations when flag `--with-kompose-annotation=false` is specified
  pkg/transformer/utils.go
  script/test/fixtures/change-in-volume/output-k8s-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-k8s.yaml
  script/test/fixtures/change-in-volume/output-os-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-os.yaml
  script/test/fixtures/compose-env-interpolation/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-k8s-withlabel.yaml
  script/test/fixtures/configmap-volume/output-os-withlabel.yaml
  script/test/fixtures/expose/output-k8s.yaml
  script/test/fixtures/expose/output-os.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v1.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v2.yaml
  script/test/fixtures/external-traffic-policy/output-os-v1.yaml
  script/test/fixtures/external-traffic-policy/output-os-v2.yaml
  script/test/fixtures/fsgroup/output-k8s.yaml
  script/test/fixtures/fsgroup/output-os.yaml
  script/test/fixtures/healthcheck/output-healthcheck-k8s.yaml
  script/test/fixtures/healthcheck/output-healthcheck-os.yaml
  script/test/fixtures/multiple-type-volumes/output-k8s.yaml
  script/test/fixtures/multiple-type-volumes/output-os.yaml
  script/test/fixtures/single-file-output/output-k8s.yaml
  script/test/fixtures/vols-subpath/output-k8s.yaml
  script/test/fixtures/vols-subpath/output-os.yaml
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved

#1755 fix: lowercase resources names
  pkg/loader/compose/compose.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/resources-lowercase/docker-compose.yaml
  script/test/fixtures/resources-lowercase/output-k8s.yaml
  script/test/fixtures/resources-lowercase/output-os.yaml
Labels: kind/bug, cncf-cla: yes, size/L, approved

#1767 updated link for daemonset
  docs/user-guide.md
Labels: kind/documentation, cncf-cla: yes, size/XS
