Repository kubernetes/kompose, pull requests merged in 2023-07, with the labels that each got.

#1659 build link update
  docs/development.md
Labels: kind/documentation, cncf-cla: yes, size/XS

#1628 feat: support container volume mount subpath
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/loader/compose/utils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/vols-subpath/docker-compose.yaml
  script/test/fixtures/vols-subpath/output-k8s.yaml
  script/test/fixtures/vols-subpath/output-os.yaml
Labels: kind/feature, cncf-cla: yes, size/L, approved

#1630 Feat add custom build push
  cmd/convert.go
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/custom-build-push/Dockerfile
  script/test/fixtures/custom-build-push/docker-compose.yaml
  script/test/fixtures/custom-build-push/output-k8s.yaml
Labels: kind/feature, cncf-cla: yes, size/L, approved

#1661 1.29.0 Release
  README.md
  build/VERSION
  docs/installation.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, approved

#1662 update release script from master to main
  script/release.sh
Labels: cncf-cla: yes, size/S, approved, kind/cleanup

#1656 Add additional Windows install method
  docs/installation.md
Labels: kind/documentation, lgtm, cncf-cla: yes, size/XS

#1669 fix: remove lower case of the host generation
  pkg/loader/compose/compose.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved

#1666 fix missing image pull secrets
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/kubernetes/podspec.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved

#1670 Feat: add read only containers support
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/read-only/docker-compose.yaml
  script/test/fixtures/read-only/output-k8s.yaml
  script/test/fixtures/read-only/output-os.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/L, approved

#1672 1.30.0 Release
  README.md
  build/VERSION
  docs/installation.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, approved

#1674 update release script again with a reminder for docs update
  script/release.sh
Labels: cncf-cla: yes

#1673 Update website with correct links
  docs/user-guide.md
Labels: kind/documentation, cncf-cla: yes, size/XS, approved

#1677 Upgrade Kubernetes module to the latest version v0.27.3
  go.mod
  go.sum
  pkg/transformer/kubernetes/podspec.go
Labels: kind/bug, cncf-cla: yes, size/L, approved

#1680 update redis wording to replica
  README.md
  examples/docker-compose-v3.yaml
  examples/docker-compose.yaml
  script/test/fixtures/controller/docker-compose.yml
  script/test/fixtures/controller/output-k8s-daemonset-template.json
  script/test/fixtures/controller/output-k8s-deployment-template.json
  script/test/fixtures/controller/output-k8s-rc-template.json
  script/test/fixtures/examples/output-k8s.json
  script/test/fixtures/examples/output-os.json
  script/test/fixtures/examples/output-v3-k8s.json
  script/test/fixtures/examples/output-v3-os.json
  script/test/fixtures/keyonly-envs/env.yml
  script/test/fixtures/keyonly-envs/output-k8s-template.json
  script/test/fixtures/unused/v3/docker-compose.yaml
  script/test/fixtures/unused/v3/output-k8s-template.json
  script/test/fixtures/unused/v3/output-os-template.json
Labels: cncf-cla: yes, size/L, approved

#1679 Fix loading env file
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests_new.sh
  script/test/cmd/update-e2e.sh
  script/test/fixtures/change-in-volume/output-k8s-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-k8s.yaml
  script/test/fixtures/change-in-volume/output-os-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-os.yaml
  script/test/fixtures/compose-file-support/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-k8s-withlabel.yaml
  script/test/fixtures/configmap-volume/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-os-withlabel.yaml
  script/test/fixtures/configmap-volume/output-os.yaml
  script/test/fixtures/deploy/placement/output-placement-k8s.yaml
  script/test/fixtures/deploy/placement/output-placement-os.yaml
  script/test/fixtures/env/docker-compose.yml
  script/test/fixtures/env/output-k8s.json
  script/test/fixtures/env/output-k8s.yaml
  script/test/fixtures/env/output-os.json
  script/test/fixtures/env/output-os.yaml
  script/test/fixtures/envvars-interpolation/output-k8s.yaml
  script/test/fixtures/envvars-interpolation/output-os.yaml
  script/test/fixtures/expose/output-k8s.yaml
  script/test/fixtures/expose/output-os.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v1.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v2.yaml
  script/test/fixtures/external-traffic-policy/output-os-v1.yaml
  script/test/fixtures/external-traffic-policy/output-os-v2.yaml
  script/test/fixtures/healthcheck/output-healthcheck-k8s.yaml
  script/test/fixtures/healthcheck/output-healthcheck-os.yaml
  script/test/fixtures/host-port-protocol/output-k8s.yaml
  script/test/fixtures/host-port-protocol/output-os.yaml
  script/test/fixtures/multiple-files/output-k8s.yaml
  script/test/fixtures/multiple-files/output-os.yaml
  script/test/fixtures/multiple-type-volumes/output-k8s.yaml
  script/test/fixtures/multiple-type-volumes/output-os.yaml
  script/test/fixtures/service-group/output-k8s.yaml
  script/test/fixtures/single-file-output/output-k8s.yaml
  script/test/fixtures/statefulset/output-k8s.yaml
  script/test/fixtures/statefulset/output-os.yaml
  script/test/fixtures/v3.0/output-k8s.yaml
  script/test/fixtures/v3.0/output-os.yaml
  script/test/fixtures/volume-mounts/windows/output-k8s.yaml
  script/test/fixtures/volume-mounts/windows/output-os.yaml
Labels: kind/bug, cncf-cla: yes, size/XXL, approved
