Repository kubernetes/kompose, pull requests merged in 2023-10, with the labels that each got.

#1725 bug: fixes bug with error out with using kompose convert with no -f
  cmd/convert.go
  pkg/app/app.go
Labels: kind/bug, cncf-cla: yes, size/S, approved

#1726 1.31.1 Release
  README.md
  build/VERSION
  docs/installation.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, approved

#1731 only add namespace if specified
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved

#1735 1.31.2 Release
  README.md
  build/VERSION
  docs/installation.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, approved

#1736 docs: update installation page to have arm64 mention
  docs/installation.md
  script/release.sh
Labels: kind/documentation, cncf-cla: yes, size/S, approved

#1737 fix e2e test
  .github/workflows/go.yml
  .github/workflows/test.yml
  pkg/transformer/openshift/openshift.go
  script/test/cmd/lib.sh
  script/test/cmd/tests_new.sh
  script/test/fixtures/change-in-volume/output-k8s-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-k8s.yaml
  script/test/fixtures/change-in-volume/output-os-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-os.yaml
  script/test/fixtures/compose-env-interpolation/docker-compose.yaml
  script/test/fixtures/compose-env-interpolation/output-k8s.yaml
  script/test/fixtures/compose-file-support/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-k8s-withlabel.yaml
  script/test/fixtures/configmap-volume/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-os-withlabel.yaml
  script/test/fixtures/configmap-volume/output-os.yaml
  script/test/fixtures/custom-build-push/Dockerfile
  script/test/fixtures/custom-build-push/docker-compose.yaml
  script/test/fixtures/custom-build-push/output-k8s.yaml
  script/test/fixtures/deploy/placement/output-placement-k8s.yaml
  script/test/fixtures/deploy/placement/output-placement-os.yaml
  script/test/fixtures/env/docker-compose.yml
  script/test/fixtures/env/output-k8s.yaml
  script/test/fixtures/env/output-os.yaml
  script/test/fixtures/envvars-interpolation/output-k8s.yaml
  script/test/fixtures/envvars-interpolation/output-os.yaml
  script/test/fixtures/expose/output-k8s.yaml
  script/test/fixtures/expose/output-os.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v1.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v2.yaml
  script/test/fixtures/external-traffic-policy/output-os-v1.yaml
  script/test/fixtures/external-traffic-policy/output-os-v2.yaml
  script/test/fixtures/fsgroup/output-k8s.yaml
  script/test/fixtures/healthcheck/docker-compose-healthcheck.yaml
  script/test/fixtures/healthcheck/output-healthcheck-k8s.yaml
  script/test/fixtures/healthcheck/output-healthcheck-os.yaml
  script/test/fixtures/host-port-protocol/output-k8s.yaml
  script/test/fixtures/host-port-protocol/output-os.yaml
  script/test/fixtures/multiple-files/output-k8s.yaml
  script/test/fixtures/multiple-files/output-os.yaml
  script/test/fixtures/multiple-type-volumes/output-k8s.yaml
  script/test/fixtures/multiple-type-volumes/output-os.yaml
  script/test/fixtures/network-policies/docker-compose.yaml
  script/test/fixtures/network-policies/output-k8s.yaml
  script/test/fixtures/read-only/output-k8s.yaml
  script/test/fixtures/read-only/output-os.yaml
  script/test/fixtures/service-group/output-k8s.yaml
  script/test/fixtures/single-file-output/output-k8s.yaml
  script/test/fixtures/statefulset/output-k8s.yaml
  script/test/fixtures/statefulset/output-os.yaml
  script/test/fixtures/v2/output-k8s.yaml
  script/test/fixtures/v2/output-os.yaml
  script/test/fixtures/v3.0/output-k8s.yaml
  script/test/fixtures/v3.0/output-os.yaml
  script/test/fixtures/vols-subpath/output-k8s.yaml
  script/test/fixtures/volume-mounts/windows/output-k8s.yaml
  script/test/fixtures/volume-mounts/windows/output-os.yaml
Labels: kind/bug, lgtm, cncf-cla: yes, size/XL, approved

#1744 fix: make transforming more deterministic
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  script/test/fixtures/service-group/output-k8s.yaml
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved

#1746 remove status field from generated yaml
  pkg/transformer/utils.go
  script/test/fixtures/change-in-volume/output-k8s-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-k8s.yaml
  script/test/fixtures/change-in-volume/output-os-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-os.yaml
  script/test/fixtures/compose-env-interpolation/output-k8s.yaml
  script/test/fixtures/compose-file-support/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-k8s-withlabel.yaml
  script/test/fixtures/configmap-volume/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-os-withlabel.yaml
  script/test/fixtures/configmap-volume/output-os.yaml
  script/test/fixtures/deploy/placement/output-placement-k8s.yaml
  script/test/fixtures/deploy/placement/output-placement-os.yaml
  script/test/fixtures/env-multiple/output-k8s.yaml
  script/test/fixtures/env-multiple/output-os.yaml
  script/test/fixtures/env/output-k8s.yaml
  script/test/fixtures/env/output-os.yaml
  script/test/fixtures/envvars-interpolation/output-k8s.yaml
  script/test/fixtures/envvars-interpolation/output-os.yaml
  script/test/fixtures/expose/output-k8s.yaml
  script/test/fixtures/expose/output-os.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v1.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v2.yaml
  script/test/fixtures/external-traffic-policy/output-os-v1.yaml
  script/test/fixtures/external-traffic-policy/output-os-v2.yaml
  script/test/fixtures/fsgroup/output-k8s.yaml
  script/test/fixtures/fsgroup/output-os.yaml
  script/test/fixtures/healthcheck/output-healthcheck-k8s.yaml
  script/test/fixtures/healthcheck/output-healthcheck-os.yaml
  script/test/fixtures/host-port-protocol/output-k8s.yaml
  script/test/fixtures/host-port-protocol/output-os.yaml
  script/test/fixtures/multiple-files/output-k8s.yaml
  script/test/fixtures/multiple-files/output-os.yaml
  script/test/fixtures/multiple-type-volumes/output-k8s.yaml
  script/test/fixtures/multiple-type-volumes/output-os.yaml
  script/test/fixtures/namespace/output-k8s.yaml
  script/test/fixtures/namespace/output-os.yaml
  script/test/fixtures/network-policies/output-k8s.yaml
  script/test/fixtures/read-only/output-k8s.yaml
  script/test/fixtures/read-only/output-os.yaml
  script/test/fixtures/service-group/output-k8s.yaml
  script/test/fixtures/single-file-output/output-k8s.yaml
  script/test/fixtures/statefulset/output-k8s.yaml
  script/test/fixtures/statefulset/output-os.yaml
  script/test/fixtures/v2/output-k8s.yaml
  script/test/fixtures/v2/output-os.yaml
  script/test/fixtures/v3.0/output-k8s.yaml
  script/test/fixtures/v3.0/output-os.yaml
  script/test/fixtures/vols-subpath/output-k8s.yaml
  script/test/fixtures/vols-subpath/output-os.yaml
  script/test/fixtures/volume-mounts/windows/output-k8s.yaml
  script/test/fixtures/volume-mounts/windows/output-os.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/XL, approved
