Repository kubernetes/kompose, pull requests merged in 2023-01, with the labels that each got.

#1547 feat: migrate from libcompose to compose-go
  .github/workflows/go.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .golangci.yml
  Makefile
  cmd/completion.go
  docs/conversion.md
  go.mod
  go.sum
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/loader/compose/compose_test.go
  pkg/loader/compose/v1v2.go
  pkg/loader/compose/v3.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/openshift/openshift.go
  pkg/transformer/openshift/openshift_test.go
  pkg/transformer/utils.go
  pkg/transformer/utils_test.go
  pkg/utils/docker/push.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/change-in-volume/output-k8s-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-k8s.yaml
  script/test/fixtures/change-in-volume/output-os-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-os.yaml
  script/test/fixtures/configmap-volume/output-k8s-withlabel.yaml
  script/test/fixtures/configmap-volume/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-os-withlabel.yaml
  script/test/fixtures/configmap-volume/output-os.yaml
  script/test/fixtures/deploy/placement/output-placement-k8s.yaml
  script/test/fixtures/deploy/placement/output-placement-os.yaml
  script/test/fixtures/envvars-interpolation/output-k8s.yaml
  script/test/fixtures/envvars-interpolation/output-os.yaml
  script/test/fixtures/expose/output-k8s.yaml
  script/test/fixtures/expose/output-os.yaml
  script/test/fixtures/healthcheck/output-healthcheck-k8s.yaml
  script/test/fixtures/healthcheck/output-healthcheck-os.yaml
  script/test/fixtures/multiple-files/output-k8s.yaml
  script/test/fixtures/multiple-files/output-os.yaml
  script/test/fixtures/multiple-type-volumes/output-k8s.yaml
  script/test/fixtures/multiple-type-volumes/output-os.yaml
  script/test/fixtures/redis-example/docker-compose.yml
  script/test/fixtures/service-group/output-k8s.yaml
  script/test/fixtures/single-file-output/output-k8s.yaml
  script/test/fixtures/statefulset/output-k8s.yaml
  script/test/fixtures/statefulset/output-os.yaml
  script/test/fixtures/v2/output-k8s.yaml
  script/test/fixtures/v2/output-os.yaml
  script/test/fixtures/v3.0/output-k8s.yaml
  script/test/fixtures/v3.0/output-os.yaml
  script/test/fixtures/volume-mounts/windows/output-k8s.yaml
  script/test/fixtures/volume-mounts/windows/output-os.yaml
  script/test_in_container/Dockerfile
Labels: cncf-cla: yes, size/XXL

#1549 Remove old scripts, modify manual syncing doc script
  script/check-gofmt.sh
  script/deploy_key
  script/deploy_key.enc
  script/generate-bintray-json.sh
  script/manual-docs-sync.sh
  script/sync-docs.sh
  script/test_in_openshift/README.md
  script/test_in_openshift/compose-files/buildconfig-relative-dirs/docker/docker-compose-build-image.yml
  script/test_in_openshift/compose-files/buildconfig-relative-dirs/docker_env.list
  script/test_in_openshift/compose-files/buildconfig-relative-dirs/server/Dockerfile
  script/test_in_openshift/compose-files/buildconfig-relative-dirs/web/Dockerfile
  script/test_in_openshift/compose-files/buildconfig/build/Dockerfile
  script/test_in_openshift/compose-files/buildconfig/docker-compose-build-image.yml
  script/test_in_openshift/compose-files/buildconfig/docker-compose.yml
  script/test_in_openshift/compose-files/docker-compose-bc-dockerfile.yml
  script/test_in_openshift/compose-files/docker-compose-command.yml
  script/test_in_openshift/compose-files/docker-compose-restart-always.yml
  script/test_in_openshift/compose-files/v2-env.yaml
  script/test_in_openshift/compose-files/v3-docker-compose-restart-always.yml
  script/test_in_openshift/compose-files/v3-docker-compose.yaml
  script/test_in_openshift/compose-files/v3-env.yaml
  script/test_in_openshift/compose-files/v3-redis-replica.yaml
  script/test_in_openshift/lib.sh
  script/test_in_openshift/run.sh
  script/test_in_openshift/tests/build.sh
  script/test_in_openshift/tests/entrypoint-command.sh
  script/test_in_openshift/tests/etherpad.sh
  script/test_in_openshift/tests/redis-replica-2.sh
  script/test_in_openshift/tests/restart-options.sh
  script/test_in_openshift/tests/routes-service-expose-hostname.sh
  script/test_in_openshift/tests/routes-service-expose-true.sh
  script/test_in_openshift/tests/v2-env.sh
  script/test_in_openshift/tests/v3-deploy.sh
  script/test_in_openshift/tests/v3-env.sh
  script/test_in_openshift/tests/v3-redis-replica.sh
  script/test_in_openshift/tests/v3-redis.sh
  script/test_in_openshift/tests/v3-restart.sh
  script/test_k8s/kubernetes.sh
  script/test_k8s/test.sh
  script/vendor-sync/types.go.txt
Labels: cncf-cla: yes, size/XXL, approved

#1550 Fix CI
  script/check-gofmt.sh
Labels: cncf-cla: yes, size/M, approved

#1552 chore: require go >=1.18, bump deps and get rid of replace directives
  go.mod
  go.sum
  pkg/loader/compose/utils.go
  pkg/testutils/git.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/utils.go
  pkg/utils/docker/build.go
  script/test/cmd/cmd_test.go
  script/test/fixtures/expose/output-os.yaml
Labels: cncf-cla: yes, size/XL, approved

#1555 owners: Remove surajssd
  OWNERS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS, approved

#1561 remove unused js files
  docs/js/background.js
  docs/js/icons.js
Labels: cncf-cla: yes, size/M, approved

#1562 1.28.0 Release
  README.md
  build/VERSION
  docs/installation.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, approved

#1563 fix small errors in release script
  script/release.sh
Labels: cncf-cla: yes, size/XS, approved

#1566 corrected broken diagram link in site
  docs/architecture.md
  docs/maven-example.md
Labels: kind/documentation, cncf-cla: yes, size/XS
