Repository kubernetes/kompose, pull requests merged in 2024-02, with the labels that each got.

#1816 docs(1815): add trademarks link ref to linux foundation
  docs/_includes/footer.html
  docs/assets/css/style.css
Labels: kind/documentation, lgtm, cncf-cla: yes, size/S, approved

#1798 fix issue 1793
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/M, approved

#1819 fix client/convert (issue https://github.com/kubernetes/kompose/issue…
  client/convert.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved

#1823 Cleanup README.md
  README.md
  docs/installation.md
Labels: kind/documentation, lgtm, cncf-cla: yes, size/XS, approved

#1799 fix issue 1778
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved

#1824 #1821 update Dockerfile to alwyas use head Alpine
  Dockerfile
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved

#1826 fix issue 1778 update1
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
Labels: cncf-cla: yes, size/M, kind/cleanup

#1831 fix issues #1829, #1830
  pkg/loader/compose/compose.go
  pkg/loader/compose/utils.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved
