Repository kubernetes/kompose, pull requests merged in 2024-03, with the labels that each got.

#1835 chore: replace AhmedGrati with TessaIO
  OWNERS
Labels: cncf-cla: yes, size/XS, approved

#1834 chore: unify e2e tests to compose yaml
  script/test/cmd/tests_new.sh
  script/test/fixtures/buildargs/compose.yaml
  script/test/fixtures/buildconfig/compose-build-no-image.yaml
  script/test/fixtures/buildconfig/compose-dockerfile.yaml
  script/test/fixtures/buildconfig/compose-v3.yaml
  script/test/fixtures/buildconfig/compose.yaml
  script/test/fixtures/change-in-volume/compose.yaml
  script/test/fixtures/compose-env-interpolation/compose.yaml
  script/test/fixtures/compose-file-env-variable/alternative-compose.yaml
  script/test/fixtures/compose-file-env-variable/compose.yaml
  script/test/fixtures/configmap-pod/compose.yaml
  script/test/fixtures/configmap-volume/compose-withlabel.yaml
  script/test/fixtures/configmap-volume/compose.yaml
  script/test/fixtures/configmap/compose.yaml
  script/test/fixtures/controller/compose-controller-label-v3.yaml
  script/test/fixtures/controller/compose-controller-label.yaml
  script/test/fixtures/controller/compose-global.yaml
  script/test/fixtures/controller/compose.yaml
  script/test/fixtures/cronjob/compose.yaml
  script/test/fixtures/deploy/placement/compose-placement.yaml
  script/test/fixtures/dockerfilepath/compose.yaml
  script/test/fixtures/domain/compose-v3.yaml
  script/test/fixtures/domain/compose.yaml
  script/test/fixtures/entrypoint-command/compose.yaml
  script/test/fixtures/env-multiple/compose.yaml
  script/test/fixtures/env/compose.yaml
  script/test/fixtures/envvars-interpolation/compose.yaml
  script/test/fixtures/envvars-separators/compose.yaml
  script/test/fixtures/external-traffic-policy/compose-v1.yaml
  script/test/fixtures/external-traffic-policy/compose-v2.yaml
  script/test/fixtures/fsgroup/compose.yaml
  script/test/fixtures/healthcheck/compose-healthcheck.yaml
  script/test/fixtures/host-port-protocol/compose.yaml
  script/test/fixtures/multiple-type-volumes/compose.yaml
  script/test/fixtures/namespace/compose.yaml
  script/test/fixtures/network-policies/compose.yaml
  script/test/fixtures/network/compose-v3.yaml
  script/test/fixtures/nginx-node-redis/compose-v3.yaml
  script/test/fixtures/nginx-node-redis/compose.yaml
  script/test/fixtures/no-profile-warning/compose.yaml
  script/test/fixtures/pvc-request-size/compose.yaml
  script/test/fixtures/read-only/compose.yaml
  script/test/fixtures/redis-example/compose.yaml
  script/test/fixtures/resources-lowercase/compose.yaml
  script/test/fixtures/single-file-output/compose.yaml
  script/test/fixtures/statefulset/compose.yaml
  script/test/fixtures/storage-class-name/compose.yaml
  script/test/fixtures/v2/compose.yaml
  script/test/fixtures/v3.0/compose.yaml
  script/test/fixtures/vols-subpath/compose.yaml
  script/test/fixtures/volume-mounts/windows/compose.yaml
Labels: cncf-cla: yes, size/L, kind/cleanup

#1841 Adds ability to specify the stage/target of a multistage dockerfile
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/transformer/utils.go
  pkg/utils/docker/build.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/S, approved
