Repository kubernetes/kompose, pull requests merged in 2024-04, with the labels that each got.

#1861 chore: fix function name in comment
  pkg/transformer/utils.go
Labels: kind/documentation, cncf-cla: yes, size/XS

#1847 Feature 1635 - added labels to generate HPA
  docs/user-guide.md
  pkg/loader/compose/utils.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/hpa/compose.yaml
  script/test/fixtures/hpa/output-k8s.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/XXL, approved

#1863 chore: fix some typos in comments
  cmd/convert.go
  cmd/root.go
  pkg/transformer/kubernetes/kubernetes_test.go
Labels: kind/documentation, cncf-cla: yes, size/XS, approved

#1852 add configmaps derived from file and dir
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/configmap-file-configs/auth.txt
  script/test/fixtures/configmap-file-configs/certs-level1/certs-level2/certs-level3/cert2.pem
  script/test/fixtures/configmap-file-configs/certs/cert1.pem
  script/test/fixtures/configmap-file-configs/compose-1.yaml
  script/test/fixtures/configmap-file-configs/compose-2.yaml
  script/test/fixtures/configmap-file-configs/compose-3.yaml
  script/test/fixtures/configmap-file-configs/output-k8s-1.yaml
  script/test/fixtures/configmap-file-configs/output-k8s-2.yaml
  script/test/fixtures/configmap-file-configs/output-k8s-3.yaml
  script/test/fixtures/configmap-file-configs/output-os-1.yaml
  script/test/fixtures/configmap-file-configs/output-os-2.yaml
  script/test/fixtures/configmap-file-configs/output-os-3.yaml
  script/test/fixtures/configmap-file-configs/users.php
Labels: kind/feature, lgtm, cncf-cla: yes, size/XXL, approved

#1848 add networkmode service:
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/network-mode-service/compose.yaml
  script/test/fixtures/network-mode-service/output-k8s.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/XXL, approved

#1854 fix 1853
  pkg/transformer/utils.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/envvars-with-status/compose.yaml
  script/test/fixtures/envvars-with-status/output-k8s.yaml
  script/test/fixtures/envvars-with-status/output-os.yaml
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved

#1865 update dependencies to last version and go 1.22
  go.mod
  go.sum
  pkg/loader/compose/compose.go
  pkg/transformer/kubernetes/kubernetes.go
Labels: kind/feature, lgtm, cncf-cla: yes, size/L, approved

#1866 1.33.0 Release
  README.md
  build/VERSION
  docs/installation.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, approved

#1869 update references to just compose
  cmd/convert.go
  cmd/root.go
  docs/architecture.md
  docs/conversion.md
  docs/getting-started.md
  docs/integrations.md
  docs/maven-example.md
  docs/user-guide.md
  index.md
  pkg/loader/compose/compose.go
  pkg/transformer/kubernetes/kubernetes.go
  script/test/fixtures/buildargs/README.md
  script/test/fixtures/etherpad/README.md
Labels: lgtm, cncf-cla: yes, size/M, approved
