Repository kubernetes/kompose, pull requests merged in 2024-01, with the labels that each got.

#1684 fix issue https://github.com/kubernetes/kompose/issues/1683
  pkg/app/app.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  pkg/transformer/utils.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/configmap-pod/bar.env
  script/test/fixtures/configmap-pod/docker-compose.yml
  script/test/fixtures/configmap-pod/foo.env
  script/test/fixtures/configmap-pod/output-k8s.yaml
  script/test/fixtures/configmap-pod/output-os.yaml
Labels: kind/bug, cncf-cla: yes, size/L, approved

#1775 feat(1765): remove useless keys from the output yml
  .gitignore
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/k8sutils_test.go
  script/test/fixtures/change-in-volume/output-k8s-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-k8s.yaml
  script/test/fixtures/change-in-volume/output-os-empty-vols-template.yaml
  script/test/fixtures/change-in-volume/output-os.yaml
  script/test/fixtures/compose-env-interpolation/output-k8s.yaml
  script/test/fixtures/compose-file-env-variable/output-k8s.yaml
  script/test/fixtures/compose-file-support/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-k8s-withlabel.yaml
  script/test/fixtures/configmap-volume/output-k8s.yaml
  script/test/fixtures/configmap-volume/output-os-withlabel.yaml
  script/test/fixtures/configmap-volume/output-os.yaml
  script/test/fixtures/deploy/placement/output-placement-k8s.yaml
  script/test/fixtures/deploy/placement/output-placement-os.yaml
  script/test/fixtures/env/output-k8s.yaml
  script/test/fixtures/env/output-os.yaml
  script/test/fixtures/envvars-interpolation/output-k8s.yaml
  script/test/fixtures/envvars-interpolation/output-os.yaml
  script/test/fixtures/expose/output-k8s.yaml
  script/test/fixtures/expose/output-os.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v1.yaml
  script/test/fixtures/external-traffic-policy/output-k8s-v2.yaml
  script/test/fixtures/external-traffic-policy/output-os-v1.yaml
  script/test/fixtures/external-traffic-policy/output-os-v2.yaml
  script/test/fixtures/fsgroup/output-k8s.yaml
  script/test/fixtures/fsgroup/output-os.yaml
  script/test/fixtures/healthcheck/output-healthcheck-k8s.yaml
  script/test/fixtures/healthcheck/output-healthcheck-os.yaml
  script/test/fixtures/host-port-protocol/output-k8s.yaml
  script/test/fixtures/host-port-protocol/output-os.yaml
  script/test/fixtures/multiple-files/output-k8s.yaml
  script/test/fixtures/multiple-files/output-os.yaml
  script/test/fixtures/multiple-type-volumes/output-k8s.yaml
  script/test/fixtures/multiple-type-volumes/output-os.yaml
  script/test/fixtures/namespace/output-k8s.yaml
  script/test/fixtures/namespace/output-os.yaml
  script/test/fixtures/network-policies/output-k8s.yaml
  script/test/fixtures/read-only/output-k8s.yaml
  script/test/fixtures/read-only/output-os.yaml
  script/test/fixtures/resources-lowercase/output-k8s.yaml
  script/test/fixtures/resources-lowercase/output-os.yaml
  script/test/fixtures/service-group/output-k8s.yaml
  script/test/fixtures/single-file-output/output-k8s.yaml
  script/test/fixtures/statefulset/output-k8s.yaml
  script/test/fixtures/statefulset/output-os.yaml
  script/test/fixtures/v2/output-k8s.yaml
  script/test/fixtures/v2/output-os.yaml
  script/test/fixtures/v3.0/output-k8s.yaml
  script/test/fixtures/v3.0/output-os.yaml
  script/test/fixtures/vols-subpath/output-k8s.yaml
  script/test/fixtures/vols-subpath/output-os.yaml
  script/test/fixtures/volume-mounts/windows/output-k8s.yaml
  script/test/fixtures/volume-mounts/windows/output-os.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/XL, approved

#1787 Initialize OpenVEX feed
  .openvex/templates/README.md
  .openvex/templates/main.openvex.json
Labels: lgtm, cncf-cla: yes, size/M, approved

#1801 test: fix e2e tests for configmap pod test
  script/test/fixtures/configmap-pod/output-k8s.yaml
  script/test/fixtures/configmap-pod/output-os.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1805 2024 copyright change
  docs/_config.yml
Labels: cncf-cla: yes, size/XS, approved

#1804 change wording for redis leader
  docs/getting-started.md
  docs/index.md
  docs/user-guide.md
Labels: kind/documentation, cncf-cla: yes, size/S, approved

#1806 Add Labels for CronJob https://github.com/kubernetes/kompose/issues/1795
  docs/user-guide.md
  pkg/kobject/kobject.go
  pkg/loader/compose/compose.go
  pkg/loader/compose/utils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/openshift/openshift.go
  script/test/cmd/tests_new.sh
  script/test/fixtures/cronjob/docker-compose.yaml
  script/test/fixtures/cronjob/output-k8s.yaml
  script/test/fixtures/cronjob/output-os.yaml
Labels: kind/feature, lgtm, cncf-cla: yes, size/L, approved

#1811 1.32.0 Release
  README.md
  build/VERSION
  docs/installation.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, approved

#1807 docs: update readme
  README.md
Labels: kind/documentation, cncf-cla: yes, size/S, approved

#1808 docs(cli): introduce examples in the kompose command
  cmd/convert.go
  cmd/root.go
Labels: kind/documentation, lgtm, cncf-cla: yes, size/S, approved

#1813 chore: update `kompose convert --help`
  cmd/convert.go
Labels: kind/documentation, lgtm, cncf-cla: yes, size/S, approved
