Repository kubernetes/kompose, pull requests merged in 2025-05, with the labels that each got.

#2011 fix: resolve env_file variable interpolation issues by adding support…
  pkg/transformer/kubernetes/k8sutils.go
  pkg/transformer/kubernetes/kubernetes.go
  pkg/transformer/kubernetes/kubernetes_test.go
  pkg/transformer/openshift/openshift.go
  script/test/cmd/tests.sh
  script/test/fixtures/envfile-interpolation/.env
  script/test/fixtures/envfile-interpolation/compose.yaml
  script/test/fixtures/envfile-interpolation/output-k8s.yaml
  script/test/fixtures/envfile-interpolation/output-os.yaml
Labels: kind/bug, lgtm, cncf-cla: yes, size/L, approved

#2008 fix: Load variables from .env file by default
  pkg/loader/compose/compose.go
  script/test/cmd/tests.sh
  script/test/fixtures/env-dotenv/.env
  script/test/fixtures/env-dotenv/compose.yaml
  script/test/fixtures/env-dotenv/output-k8s.yaml
  script/test/fixtures/env-dotenv/output-os.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved

#2013 1.36.0 Release
  README.md
  build/VERSION
  docs/installation.md
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, approved
